#!/bin/bash

# Source the config file or die...
. /etc/linuxmuster/ddns.conf || exit 1

if [ "x$HOST" == "x" ]; then
 echo "host to be updated must be given as argument one"
 echo "doing nothing, exit."
 exit 0
fi

TIMESTAMP=$(date +%Y-%m-%d-%H-%M)
DNS_IP=$(host $HOST 8.8.8.8 | grep has | awk '{print $4}' | tr -d '[:blank:]')
REAL_IP=$(wget -q http://checkip.twodns.de/ -O - | awk -F: '{print $2}' | awk -F"<" '{print $1}' | tr -d '[:blank:]')

if [ "$REAL_IP" = "$DNS_IP" ]; then
  echo "$TIMESTAMP linuxmuster-ddns OK: $HOST has IP $REAL_IP"
  exit 0
else
 echo "$TIMESTAMP linuxmuster-ddns UPDATE: $HOST has DNS-IP $DNS_IP but real-IP is $REAL_IP"
 #echo "Executing:  curl -q -k -v -G -d hostname=$HOST -d username=$USER -d password=$PASS  ${UPDATEURI} > /dev/null 2>&1"
 curl -q -k -v -G -d hostname=$HOST -d username=$USER -d password=$PASS  ${UPDATEURI} > /dev/null 2>&1
fi


